# Generated by Django 5.0.3 on 2024-05-19 01:05

import django.db.models.deletion
import gestao_caixa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cargo_nome'),
        ('gestao_caixa', '0002_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=300)),
                ('sobrenome', models.TextField(max_length=300)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[gestao_caixa.models.validate_cpf])),
                ('data_nascimento', models.DateTimeField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cargo')),
            ],
        ),
    ]
