# Generated by Django 5.0.3 on 2024-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cargo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(choices=[('Recepcionista', 'Recepcionista'), ('Professor(a)', 'Professor(a)'), ('Professor(a) de dança', 'Professor(a) de dança'), ('Professor(a) de crossfit', 'Professor(a) de crossfit'), ('Sócio(a)', 'Sócio(a)'), ('Serviços Gerais', 'Serviços Gerais')], max_length=100),
        ),
    ]
